
arch:
    backbone     : resnet34v3
    pooling      : twostageavg
    n_classes    : 2
    embedding    : 512
slide:
data:
    dataset : milFolder 
    classmap: 
      mss: 0 
      msi: 1
    
    # AMC lib location
    data_path    : "./research_mil/data/amc_2020/msi_test_temp/"
    test_split   : "test"
    nslides      : 1 
training:
    test_batch_size : 1     # 1
    resume: mil_model.pth
testing:
    ############################################################################################################
    # Using PRETRAINED MODELS
    # NOTE : Do not re-train with pre-trained models, use for testing only.
    # Checkpoint is loaded from (root,checkpoint)
    checkpoint: 'checkpoints/pretrained/patch_encoder/mil_model.pth' 
    logdir    : 'checkpoints/amc_mssmsi/patch_encoder/test_seg_full'
    ###########################################################################################################
    threshold_list: '0.5' # default: '0.1,0.2,0.3,0.4,0.5'
    threshold     : 0.5
    # Location of tissue, tumor masks
    masks         : "/media/philipchicco/CHICCO4TB/Development/Data/MSSMSI/AMCData/AMC_ALL"
    

# Pretrained models
# NOTE : Do not re-train with pre-trained models, use for testing only.
# Model is saved in (root,logdir)
root  : './research_mil/logs'
logdir: 'checkpoints/amc_mssmsi/patch_encoder'
############################################################################################################
